service: cle-roboto-serverless

# app and org for use with dashboard.serverless.com
app: probot-hello-world-example
org: probot

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  environment:
    APP_ID: ${param:APP_ID}
    PRIVATE_KEY: ${param:PRIVATE_KEY}
    WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: index.handler
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post